config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :shows do
    resources :tickets, only: [:new, :create]  # or include other actions as needed
  end
  resources :movies do
    resources :shows do
      resources :tickets
    end
  end
  resources :admins, only: [:index,:new,:edit, :update]
  root 'home#index'
  resources :users
  resources :admin_sessions, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get 'manage_users', to: "users#index", as: "manage_users"
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'admin_login', to: "admin_sessions#new", as: 'admin_login'
  get 'admin_logout', to: "admin_sessions#destroy", as: 'admin_logout'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]
  skip_before_action :authorized_admin, only: [:index]
  
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to the Movie Ticketing System</h1>

<% if current_admin %>
    Logged in as Admin <%= current_admin.name%>.<br>
    <%= link_to "Manage movies", movies_path %><br>
    <%= link_to "Manage tickets", tickets_path %><br>
    <%= link_to "Manage Users", manage_users_path%><br>
    <%= link_to "Edit profile", edit_admin_path(current_admin.id) %><br>
    <%= link_to "Logout", admin_logout_path %><br>

<% elsif current_user %>
    Logged in as <%= current_user.name %>.<br>
    <%= link_to 'View movies', movies_path %><br>
    <%= link_to 'View Profile', manage_users_path %><br>
    <%= link_to "View your tickets", tickets_path%><br>
    <%= link_to "Logout", logout_path %>

<% else %>
    <%= link_to "Signup", signup_path %> or
    <%= link_to "Login", login_path %><br>
    <%= link_to "Login as Admin", admin_login_path %>
<% end %>