config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :shows do
    resources :tickets, only: [:new, :create]  # or include other actions as needed
  end
  resources :movies do
    resources :shows do
      resources :tickets
    end
  end
  resources :admins, only: [:index,:new,:edit, :update]
  root 'home#index'
  resources :users
  resources :admin_sessions, only: [:new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get 'manage_users', to: "users#index", as: "manage_users"
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'admin_login', to: "admin_sessions#new", as: 'admin_login'
  get 'admin_logout', to: "admin_sessions#destroy", as: 'admin_logout'
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :movie
  has_many :tickets, dependent: :destroy

  validates :date, :time, :seats, :price, :available_seats, presence: true
  validates :movie_id, presence: true  # Ensure show is linked to an existing movie
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  # Show all movies in the drop-down
  def index
    @movie = Movie.find_by(id: params[:movie_id])  # Safely finding the movie by ID
    @shows = @movie.shows
  end

  def new
    @show = Show.new
    @movies = Movie.all  # Fetch all movies
    @selected_movie = Movie.find_by(id: params[:movie_id]) 
  end

  def edit 
    @show = Show.find(params[:id])
    @movies = Movie.all
  end

  def update
    @show = Show.find(params[:id])
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # Create a new show and associate it with the selected movie
  def create
    @show = Show.new(show_params)
    @movie = Movie.find_by(id: params[:show][:movie_id])  # Find the movie by ID
    @show.available_seats = @show.seats
    if @movie
      @show.movie = @movie  # Associate the show with the selected movie
      respond_to do |format|
        if @show.save
          format.html { redirect_to @show, notice: "Show was successfully created." }
          format.json { render :show, status: :created, location: @show }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @show.errors, status: :unprocessable_entity }
        end
      end
    end  
  end

  def show
    @show = Show.find(params[:id])
  end

  def destroy
    @show = Show.find(params[:id])
    @movie = @show.movie
    @show.tickets.destroy_all
    @show.destroy!

    respond_to do |format|
      format.html { redirect_to movie_shows_path(@movie), status: :see_other, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private

  # Strong params to handle show fields
  def show_params
    params.require(:show).permit( :movie_id, :date, :time, :seats, :price, :available_seats)
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= form.label :movie_id, "Select Movie" %>
  <%= form.collection_select :movie_id, @movies, :id, :title, { prompt: "Select a Movie", selected: @selected_movie&.id }, class: "form-control" %>
  </div>

  
  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.time_field :time %>
  </div>

  <div>
    <%= form.label :seats, style: "display: block" %>
    <%= form.number_field :seats %>
  </div>

  <div>
    <%= form.label :ticket_price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_show.html.erb
<div id="<%= dom_id show %>">
  <p>
    <strong>Movie:</strong>
    <%= show.movie.title %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= show.date %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= show.time.strftime("%I:%M %p") %>

  </p>

  <p>
    <strong>Seats:</strong>
    <%= show.seats %>
  </p>

  <p>
    <strong>Available Seats:</strong>
    <%= show.available_seats %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= show.price %>
  </p>

</div>

app/views/shows/edit.html.erb
<% content_for :title, "Editing show" %>

<h1>Editing show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Show this show", @show %> |
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Shows" %>

<h1>Shows</h1>

<div id="shows">
  <% @shows.each do |show| %>
    <%= render show %>
    <p>
      <%= link_to "Show this show", show %> |
      <%= link_to "Purchase Tickets", new_movie_show_ticket_path(@movie, show)%>
    </p>
  <% end %>
</div>

<%if current_admin %>
  <%= link_to "New show", new_show_path %> |
<% end %>

<%= link_to "Back to Main Menu", root_path %> | 
<%= link_to "Back to Movies", movies_path %>

app/views/shows/new.html.erb
<% content_for :title, "New show" %>

<h1>New show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/shows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @show %>

<div>
  <%= link_to "Edit this show", edit_show_path(@show) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this show", @show, method: :delete %>
</div>